# Prometheus config for Besu IBFT2 running on Kubernetes
# Metrics are exposed via NodePort services on the K8s host
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files: []

scrape_configs:
    - job_name: besu-0
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
        - targets: [ 'besu-rpc:30950' ]
          labels:
            node: 'besu-0'
            role: 'bootnode'

    - job_name: besu-1
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
        - targets: [ 'besu-rpc:30951' ]
          labels:
            node: 'besu-1'
            role: 'validator'

    - job_name: besu-2
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
        - targets: [ 'besu-rpc:30952' ]
          labels:
            node: 'besu-2'
            role: 'validator'

    - job_name: besu-3
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
        - targets: [ 'besu-rpc:30953' ]
          labels:
            node: 'besu-3'
            role: 'validator'

